export const carArray = [
	{
        id: 1,
        img: '../mga-mini_l500_h750.png',
        name: 'MG A',
        brand: 'MG',
        model: 'A',
        production: '1955 to 1962',
        engineType: '4 inline cylinders',
        engine: '1.5L and 1.6L',
        bodyType: "roadster or coupé (2-seater)",
        bhp: '68ch to 108ch',
        weight:'890kg',
        gearbox: 'manual, 4 speed',
        gearboxBrand: 'MG',
        maxSpeed: '155km/h to 182km/h',
    },
    {
        id: 2,
        img: '../mgb-mini_l500_h750.png',
        name: 'MG B',
        brand: 'MG',
        model: 'B',
        production: '1962 to 1980',
        engineType: 'inline cylinders: 4 or 6, and V8',
        engine: '1.8L (4 cyl.), 3L (6 cyl.) and 3.5L (V8)',
        bodyType: "roadster or coupé (2-seater)",
        bhp: '95ch',
        weight:'920kg',
        gearbox: 'automatic, 4 speed',
        gearboxBrand: 'BorgWarner',
        maxSpeed: '170km/h',
    }
];
